[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "taxi route narrow refuse measure pencil mom air sausage double wage disagree embrace tape deny vague witness pen wisdom fold napkin know machine tortoise"
